### ISSUE TITLE
¿Repositorio desactualizado?

### ISSUE THREAD

**Issue by jonalvarezz** [codeisintheair/payulatam-woocommerce#2]
Hola!

Estaba revisando tu plugin y noté que está des actualizado en comparación con el que tienes en [Wordpress](https://wordpress.org/plugins/woocommerce-payu-latam-gateway/), ya no estás manteniendo este repositorio o se encuentra en otro lugar? Me gustaría realizar alguno cambios y aportar.

**Comment by digitalhydra** [comment]
Hola, si aun estoy manteniendolo solo que no volvi a subir las ultimas versiones a github. si quieres puedes colaborar tambien.

**Comment by jonalvarezz** [comment]
Hola Jairo, si me interesa. Donde consigo la última versión entonces para partir de ahí

**Comment by digitalhydra** [comment]
la puedes descargar del repositorio de wordpress.
